name: spotify_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


 
  path: ^1.9.0
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.0.11
  firebase_core: ^3.6.0 
  firebase_auth: ^5.3.1 
  get_it: ^8.0.0
  dartz: ^0.10.0
  cloud_firestore: ^5.4.3
  just_audio: ^0.9.40
  ffmpeg_kit_flutter: ^6.0.3
  id3_codec: ^1.0.3 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 300

