// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvDlYESHPcUsTSTSxiZQWHDYst3YREYzA',
    appId: '1:1051431401822:web:f340f9cf5dc021cf5cf7cf',
    messagingSenderId: '1051431401822',
    projectId: 'spotify-team',
    authDomain: 'spotify-team.firebaseapp.com',
    storageBucket: 'spotify-team.appspot.com',
    measurementId: 'G-K0GB0P16Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjRPUIpdmhhNVLz6_TvxaloAFOTFt9QXM',
    appId: '1:1051431401822:android:01c2e7851f4743385cf7cf',
    messagingSenderId: '1051431401822',
    projectId: 'spotify-team',
    storageBucket: 'spotify-team.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyZNC16NWo3Z11Qobb-KcdI1eM2G_CCWg',
    appId: '1:1051431401822:ios:974a07e4ca32cc845cf7cf',
    messagingSenderId: '1051431401822',
    projectId: 'spotify-team',
    storageBucket: 'spotify-team.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyZNC16NWo3Z11Qobb-KcdI1eM2G_CCWg',
    appId: '1:1051431401822:ios:974a07e4ca32cc845cf7cf',
    messagingSenderId: '1051431401822',
    projectId: 'spotify-team',
    storageBucket: 'spotify-team.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvDlYESHPcUsTSTSxiZQWHDYst3YREYzA',
    appId: '1:1051431401822:web:3ae8856f1bf9f44f5cf7cf',
    messagingSenderId: '1051431401822',
    projectId: 'spotify-team',
    authDomain: 'spotify-team.firebaseapp.com',
    storageBucket: 'spotify-team.appspot.com',
    measurementId: 'G-N7DG5BPG5Q',
  );
}
